/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DailyGoal = bigint;
export interface DayStats { 'reps' : bigint, 'sets' : bigint }
export type Time = bigint;
export interface TrendDay { 'reps' : bigint, 'dayStart' : Time }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats { 'dailyTrends' : Array<TrendDay> }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  '_resetDailyStats' : ActorMethod<[null], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDayStats' : ActorMethod<[bigint], [] | [DayStats]>,
  'getDayStatsForUser' : ActorMethod<[Principal, bigint], [] | [DayStats]>,
  'getDayTotal' : ActorMethod<[bigint], [] | [bigint]>,
  'getDayTotalForUser' : ActorMethod<[Principal, bigint], [] | [bigint]>,
  'getTodayGoal' : ActorMethod<[null], [] | [DailyGoal]>,
  'getTodayStats' : ActorMethod<[null], [] | [DayStats]>,
  'getTodayTotal' : ActorMethod<[null], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'hasEntriesToday' : ActorMethod<[null], boolean>,
  'incrementTodayTotal' : ActorMethod<[bigint], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTodayGoal' : ActorMethod<[DailyGoal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];