/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DayStats = IDL.Record({ 'reps' : IDL.Nat, 'sets' : IDL.Nat });
export const DailyGoal = IDL.Nat;
export const Time = IDL.Int;
export const TrendDay = IDL.Record({ 'reps' : IDL.Nat, 'dayStart' : Time });
export const UserStats = IDL.Record({ 'dailyTrends' : IDL.Vec(TrendDay) });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  '_resetDailyStats' : IDL.Func([IDL.Null], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayStats' : IDL.Func([IDL.Nat], [IDL.Opt(DayStats)], ['query']),
  'getDayStatsForUser' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(DayStats)],
      ['query'],
    ),
  'getDayTotal' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getDayTotalForUser' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getTodayGoal' : IDL.Func([IDL.Null], [IDL.Opt(DailyGoal)], ['query']),
  'getTodayStats' : IDL.Func([IDL.Null], [IDL.Opt(DayStats)], ['query']),
  'getTodayTotal' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'hasEntriesToday' : IDL.Func([IDL.Null], [IDL.Bool], ['query']),
  'incrementTodayTotal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTodayGoal' : IDL.Func([DailyGoal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DayStats = IDL.Record({ 'reps' : IDL.Nat, 'sets' : IDL.Nat });
  const DailyGoal = IDL.Nat;
  const Time = IDL.Int;
  const TrendDay = IDL.Record({ 'reps' : IDL.Nat, 'dayStart' : Time });
  const UserStats = IDL.Record({ 'dailyTrends' : IDL.Vec(TrendDay) });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    '_resetDailyStats' : IDL.Func([IDL.Null], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayStats' : IDL.Func([IDL.Nat], [IDL.Opt(DayStats)], ['query']),
    'getDayStatsForUser' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(DayStats)],
        ['query'],
      ),
    'getDayTotal' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getDayTotalForUser' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getTodayGoal' : IDL.Func([IDL.Null], [IDL.Opt(DailyGoal)], ['query']),
    'getTodayStats' : IDL.Func([IDL.Null], [IDL.Opt(DayStats)], ['query']),
    'getTodayTotal' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'hasEntriesToday' : IDL.Func([IDL.Null], [IDL.Bool], ['query']),
    'incrementTodayTotal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTodayGoal' : IDL.Func([DailyGoal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };